tasks:
  backend: minsky
persistence:
  backend: postgres
logger:
  mode: auto
  level: info
  enableAgentLogs: false
repository:
  backend: github
  url: https://github.com/edobry/flowtato.git
  github:
    owner: edobry
    repo: flowtato
project:
  slug: edobry/flowtato
